dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.3.2"
  - "bugout-dev/dao@0.0.3"

compiler:
  solc:
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@moonstream=bugout-dev/dao@0.0.3"
